"""
OFF 360 — Iteration 11 backend regression: remote request confirm flow + responses + wa-click.

Focus:
 - NEW GET /api/merchant/requests/{rid} — returns detail, 404 for foreign owners
 - merchant_respond appends to responses[] array (multiple responses accumulate)
 - Notification of respond has preview "<estab> respondeu: <texto...>" + link "/my-requests?req=<id>"
 - POST /api/merchant/requests/{rid}/wa-click — increments counter, DOES NOT change status
 - Confirm idempotent: 5% of 100 -> 5 saved, 95 final; second call yields same tx_id and does not
   double total_saved / total_spent / tickets
 - Confirm on already-completed remote request returns 200 with same tx (no 404)
 - Confirm on cancelled -> 400 (friendly), still idempotent-safe
 - Notifications generated by accept/respond/confirm all link to /my-requests?req=<rid>
 - Ownership isolation: foreign merchant get/detail/wa-click -> 404

All entities created with QA_AUTOMATED_ prefix.
"""
import os, uuid, pytest, requests

def _load_backend_url():
    v = os.environ.get("REACT_APP_BACKEND_URL")
    if v:
        return v.rstrip("/")
    with open("/app/frontend/.env") as f:
        for line in f:
            if line.startswith("REACT_APP_BACKEND_URL="):
                return line.split("=", 1)[1].strip().rstrip("/")
    raise RuntimeError("no backend url")

BASE = _load_backend_url()
ADMIN = {"email": "qa_admin@off360.com", "password": "QaAdmin@2026"}
PASS = "QaPass@2026"


def _hex(): return uuid.uuid4().hex[:10]


def _session():
    s = requests.Session()
    s.headers.update({"Content-Type": "application/json"})
    return s


def _login(s, email, password):
    r = s.post(f"{BASE}/api/auth/login", json={"email": email, "password": password})
    assert r.status_code == 200, f"login failed: {r.status_code} {r.text}"
    return r.json()


def _register(s, role):
    h = _hex()
    email = f"qa_automated_{h}@testoff360.com"
    body = {"name": f"QA_AUTOMATED_{role}_{h}", "email": email, "phone": "11999990000",
            "password": PASS, "role": role, "city": "SP", "neighborhood": "Centro"}
    if role == "merchant":
        body.update({"fantasy_name": f"QA_AUTOMATED_FN_{h}", "category_id": None})
    r = s.post(f"{BASE}/api/auth/register", json=body)
    assert r.status_code == 200, f"register {role}: {r.status_code} {r.text}"
    return r.json(), email


@pytest.fixture(scope="module")
def admin_sess():
    s = _session()
    try:
        _login(s, ADMIN["email"], ADMIN["password"])
    except AssertionError:
        s2 = _session()
        _login(s2, "paulo.silva.dn.0006@gmail.com", "Off360Admin!2026")
        _login(s, ADMIN["email"], ADMIN["password"])
    return s


@pytest.fixture(scope="module")
def created():
    return {"users": [], "establishments": [], "requests": [], "transactions": []}


def _make_merchant_with_active_est(admin_sess, created, discount_percent=5, whatsapp="5511999998888"):
    m_sess = _session()
    m_user, _ = _register(m_sess, "merchant")
    created["users"].append(m_user["id"])
    r = m_sess.post(f"{BASE}/api/merchant/establishments", json={
        "fantasy_name": f"QA_AUTOMATED_EST_{_hex()}",
        "description": "QA est", "address": "Rua QA 1", "neighborhood": "Centro", "city": "SP",
        "discount_percent": discount_percent, "whatsapp": whatsapp,
    })
    assert r.status_code == 200, r.text
    est = r.json()
    created["establishments"].append(est["id"])
    r = admin_sess.post(f"{BASE}/api/admin/merchants/{m_user['id']}/activate"); assert r.status_code == 200, r.text
    r = admin_sess.post(f"{BASE}/api/admin/establishments/{est['id']}/activate"); assert r.status_code == 200, r.text
    r = m_sess.put(f"{BASE}/api/merchant/establishment/{est['id']}", json={
        "discount_min_purchase": 0, "whatsapp": whatsapp,
    })
    assert r.status_code == 200, r.text
    return m_sess, m_user, est


def _make_active_consumer(admin_sess, created):
    c_sess = _session()
    c_user, _ = _register(c_sess, "consumer")
    created["users"].append(c_user["id"])
    r = admin_sess.post(f"{BASE}/api/admin/consumers/{c_user['id']}/activate"); assert r.status_code == 200, r.text
    return c_sess, c_user


def _btn(**kw):
    base = {"enabled": True, "label": "Agendar", "service_type": "agendamento",
            "destination": "internal", "whatsapp_message": "", "external_url": "",
            "valid_days": [], "hours_start": "", "hours_end": "",
            "response_time": "24h", "observations": "", "discount_valid": True,
            "requires_prepayment": False, "delivery_fee": None, "areas": "", "deadline": ""}
    base.update(kw)
    return base


def _create_request(c_sess, est_id, btn_id, **extra):
    body = {"establishment_id": est_id, "button_id": btn_id,
            "product_service": "Serviço QA", "desired_date": "2026-08-13",
            "desired_time": "12:05", "phone": "11988887777", "message": "QA msg"}
    body.update(extra)
    r = c_sess.post(f"{BASE}/api/consumer/requests", json=body)
    assert r.status_code == 200, r.text
    return r.json()


# ---------- NEW GET /merchant/requests/{rid} ----------
def test_merchant_get_request_detail_and_ownership(admin_sess, created):
    m_sess, m_user, est = _make_merchant_with_active_est(admin_sess, created)
    buttons = [_btn()]
    r = m_sess.put(f"{BASE}/api/merchant/establishment/{est['id']}", json={"action_buttons": buttons})
    btn_id = r.json()["establishment"]["action_buttons"][0]["id"]

    c_sess, _ = _make_active_consumer(admin_sess, created)
    req = _create_request(c_sess, est["id"], btn_id)
    rid = req["id"]; created["requests"].append(rid)

    # owner GET detail
    r = m_sess.get(f"{BASE}/api/merchant/requests/{rid}")
    assert r.status_code == 200, r.text
    d = r.json()
    assert d["id"] == rid
    assert d["code"] == req["code"]
    assert d["status"] == "awaiting"

    # foreign merchant -> 404
    m2, _, _ = _make_merchant_with_active_est(admin_sess, created)
    r = m2.get(f"{BASE}/api/merchant/requests/{rid}")
    assert r.status_code == 404, r.text


# ---------- responses[] array + preview + link ----------
def test_merchant_respond_appends_and_notifies_with_preview_and_link(admin_sess, created):
    m_sess, _, est = _make_merchant_with_active_est(admin_sess, created)
    buttons = [_btn()]
    r = m_sess.put(f"{BASE}/api/merchant/establishment/{est['id']}", json={"action_buttons": buttons})
    btn_id = r.json()["establishment"]["action_buttons"][0]["id"]

    c_sess, _ = _make_active_consumer(admin_sess, created)
    req = _create_request(c_sess, est["id"], btn_id)
    rid = req["id"]; created["requests"].append(rid)

    # first response
    msg1 = "Podemos atender às 14h amanhã."
    r = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/respond", json={"message": msg1})
    assert r.status_code == 200, r.text
    d = r.json()
    assert d["merchant_response"] == msg1
    assert isinstance(d.get("responses"), list) and len(d["responses"]) == 1
    assert d["responses"][0]["message"] == msg1
    assert d["responses"][0].get("at")

    # second (very long) response
    long_msg = "Tudo bem! " + ("Detalhes muito longos " * 20)
    r = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/respond", json={"message": long_msg})
    assert r.status_code == 200, r.text
    d = r.json()
    assert len(d["responses"]) == 2
    assert d["responses"][-1]["message"] == long_msg
    assert d["merchant_response"] == long_msg

    # Consumer notifications: latest is the respond, with preview + link
    r = c_sess.get(f"{BASE}/api/notifications")
    assert r.status_code == 200, r.text
    notifs = r.json()["items"]
    # Find respond notification for this establishment
    resp_notifs = [n for n in notifs if n.get("title") == "Resposta do estabelecimento"
                   and est["fantasy_name"] in (n.get("message") or "")]
    if len(resp_notifs) < 2:
        print("DEBUG notifs sample:", [(n.get("title"), n.get("message"), n.get("link")) for n in notifs[:8]])
        print("DEBUG est fantasy_name:", est["fantasy_name"])
    assert len(resp_notifs) >= 2, f"expected >=2 respond notifs, got: {resp_notifs}"
    latest = resp_notifs[0]
    # message should contain preview of message (truncated to 60 + …)
    assert "respondeu:" in latest["message"], latest
    # link must point to /my-requests?req=<rid>
    assert latest.get("link") == f"/my-requests?req={rid}", latest
    # preview cap at ~60 chars for long message
    preview_part = latest["message"].split("respondeu:", 1)[1].strip()
    assert "…" in preview_part or len(preview_part) <= 65


# ---------- wa-click endpoint ----------
def test_merchant_wa_click_does_not_change_status(admin_sess, created):
    m_sess, _, est = _make_merchant_with_active_est(admin_sess, created)
    buttons = [_btn()]
    r = m_sess.put(f"{BASE}/api/merchant/establishment/{est['id']}", json={"action_buttons": buttons})
    btn_id = r.json()["establishment"]["action_buttons"][0]["id"]

    c_sess, _ = _make_active_consumer(admin_sess, created)
    req = _create_request(c_sess, est["id"], btn_id)
    rid = req["id"]; created["requests"].append(rid)

    # baseline
    prev = m_sess.get(f"{BASE}/api/merchant/requests/{rid}").json()
    assert prev["status"] == "awaiting"

    r = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/wa-click")
    assert r.status_code == 200, r.text

    # status unchanged, wa clicks incremented
    d = m_sess.get(f"{BASE}/api/merchant/requests/{rid}").json()
    assert d["status"] == "awaiting"
    assert d.get("merchant_wa_clicks", 0) == 1

    # 2nd click -> counter 2, still awaiting
    m_sess.post(f"{BASE}/api/merchant/requests/{rid}/wa-click")
    d = m_sess.get(f"{BASE}/api/merchant/requests/{rid}").json()
    assert d["status"] == "awaiting"
    assert d.get("merchant_wa_clicks", 0) == 2

    # foreign merchant -> 404
    m2, _, _ = _make_merchant_with_active_est(admin_sess, created)
    r = m2.post(f"{BASE}/api/merchant/requests/{rid}/wa-click")
    assert r.status_code == 404


# ---------- Confirm 5% idempotency ----------
def test_confirm_5pct_idempotent_no_double_side_effects(admin_sess, created):
    m_sess, _, est = _make_merchant_with_active_est(admin_sess, created, discount_percent=5)
    buttons = [_btn()]
    r = m_sess.put(f"{BASE}/api/merchant/establishment/{est['id']}", json={"action_buttons": buttons})
    btn_id = r.json()["establishment"]["action_buttons"][0]["id"]

    c_sess, c_user = _make_active_consumer(admin_sess, created)
    req = _create_request(c_sess, est["id"], btn_id)
    rid = req["id"]; created["requests"].append(rid)
    assert req["discount_percent"] == 5

    # baseline economy + tickets
    r = c_sess.get(f"{BASE}/api/consumer/economy")
    econ0 = r.json()
    saved0 = econ0["total_saved"]
    spent0 = econ0.get("total_spent", 0)
    r = c_sess.get(f"{BASE}/api/auth/me")
    me0 = r.json()
    tickets0 = me0.get("ticket_count", 0)

    # accept then confirm
    m_sess.post(f"{BASE}/api/merchant/requests/{rid}/accept")

    r = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/confirm", json={"gross_amount": 100})
    assert r.status_code == 200, r.text
    d = r.json()
    assert d["status"] == "completed"
    assert d["discount_amount"] == 5.0
    assert d["saved_amount"] == 5.0
    assert d["final_amount"] == 95.0
    tx_id = d["transaction_id"]
    assert tx_id
    created["transactions"].append(tx_id)

    # SECOND confirm same request -> same tx, NO duplicate side-effects
    r2 = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/confirm", json={"gross_amount": 100})
    assert r2.status_code == 200, r2.text
    d2 = r2.json()
    assert d2["transaction_id"] == tx_id
    assert d2["status"] == "completed"

    # THIRD, no body -> still same tx
    r3 = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/confirm", json={})
    assert r3.status_code == 200, r3.text
    assert r3.json()["transaction_id"] == tx_id

    # Check no duplicate transactions in economy history
    r = c_sess.get(f"{BASE}/api/consumer/economy")
    econ1 = r.json()
    match = [t for t in econ1["history"] if t["id"] == tx_id]
    assert len(match) == 1
    # total_saved incremented exactly by 5
    assert round(econ1["total_saved"] - saved0, 2) == 5.0

    # tickets not doubled (whatever rule adds, only once)
    r = c_sess.get(f"{BASE}/api/auth/me")
    tickets1 = r.json().get("ticket_count", 0)
    delta_tickets = tickets1 - tickets0
    assert delta_tickets >= 0
    # can't assert exact tickets since depends on rules, but the delta after 3 confirms must equal delta after 1
    r4 = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/confirm", json={"gross_amount": 100})
    assert r4.status_code == 200
    r = c_sess.get(f"{BASE}/api/auth/me")
    tickets2 = r.json().get("ticket_count", 0)
    assert tickets2 == tickets1, f"tickets doubled: {tickets1} -> {tickets2}"


# ---------- Confirm friendly guards ----------
def test_confirm_on_cancelled_is_400_not_404(admin_sess, created):
    m_sess, _, est = _make_merchant_with_active_est(admin_sess, created)
    buttons = [_btn()]
    r = m_sess.put(f"{BASE}/api/merchant/establishment/{est['id']}", json={"action_buttons": buttons})
    btn_id = r.json()["establishment"]["action_buttons"][0]["id"]

    c_sess, _ = _make_active_consumer(admin_sess, created)
    req = _create_request(c_sess, est["id"], btn_id)
    rid = req["id"]; created["requests"].append(rid)
    c_sess.post(f"{BASE}/api/consumer/requests/{rid}/cancel")

    r = m_sess.post(f"{BASE}/api/merchant/requests/{rid}/confirm", json={"gross_amount": 100})
    assert r.status_code == 400, r.text  # not 404
    # error message must be friendly Portuguese, not raw axios/exception
    body = r.text.lower()
    assert "não pode" in body or "nao pode" in body


def test_confirm_nonexistent_id_is_404_but_backend_supplies_message(admin_sess, created):
    m_sess, _, est = _make_merchant_with_active_est(admin_sess, created)
    fake_id = "does-not-exist-" + _hex()
    r = m_sess.post(f"{BASE}/api/merchant/requests/{fake_id}/confirm", json={"gross_amount": 100})
    assert r.status_code == 404, r.text
    # Backend still returns Portuguese detail (frontend formatApiError converts to friendly text)
    assert "solicita" in r.text.lower() or "not" in r.text.lower()


# ---------- Notifications link format ----------
def test_notifications_link_to_my_requests_with_req(admin_sess, created):
    m_sess, _, est = _make_merchant_with_active_est(admin_sess, created)
    buttons = [_btn()]
    r = m_sess.put(f"{BASE}/api/merchant/establishment/{est['id']}", json={"action_buttons": buttons})
    btn_id = r.json()["establishment"]["action_buttons"][0]["id"]

    c_sess, _ = _make_active_consumer(admin_sess, created)
    req = _create_request(c_sess, est["id"], btn_id)
    rid = req["id"]; created["requests"].append(rid)

    m_sess.post(f"{BASE}/api/merchant/requests/{rid}/accept")
    m_sess.post(f"{BASE}/api/merchant/requests/{rid}/respond", json={"message": "oi"})
    m_sess.post(f"{BASE}/api/merchant/requests/{rid}/confirm", json={"gross_amount": 50})

    r = c_sess.get(f"{BASE}/api/notifications")
    assert r.status_code == 200
    notifs = r.json()["items"]
    # take last 5 (most recent for this consumer) and expect at least accept+respond+completed to link to /my-requests?req=<rid>
    linked = [n for n in notifs if n.get("link") == f"/my-requests?req={rid}"]
    assert len(linked) >= 3, f"expected >=3 notifs linking to /my-requests?req={rid}, got {[n.get('link') for n in notifs[:10]]}"


# ---------- Cleanup ----------
def test_cleanup(admin_sess, created):
    for tid in created["transactions"]:
        try:
            admin_sess.post(f"{BASE}/api/admin/transactions/{tid}/cancel")
        except Exception:
            pass
    for eid in created["establishments"]:
        try:
            admin_sess.post(f"{BASE}/api/admin/establishments/{eid}/suspend")
        except Exception:
            pass
